"use client";
import { CopyPlus, Eye, Save, Send } from "lucide-react";
import { useState } from "react";
import type { PricingCatalogDocument } from "@/lib/pricing/catalog-contracts";
import styles from "./PricingCatalogManager.module.css";

type Definition = PricingCatalogDocument["definitions"][number];
type ImportedModel = NonNullable<Definition["importedModels"]>[number];
type ImportedVariant = ImportedModel["variants"][number];

export function PricingCatalogManager({ initialDraft, publishedVersion }: { initialDraft: PricingCatalogDocument; publishedVersion: number }) {
  const [draft, setDraft] = useState(initialDraft); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState("");
  const updateDefinition = (productId: string, mutate: (value: Definition) => Definition) => setDraft((current) => ({ ...current, definitions: current.definitions.map((item) => item.productId === productId ? mutate(item) : item) }));
  const updateModel = (productId: string, modelId: string, mutate: (model: ImportedModel) => ImportedModel) => updateDefinition(productId, (item) => ({ ...item, importedModels: item.importedModels?.map((model) => model.id === modelId ? mutate(model) : model) }));
  const updateVariant = (productId: string, modelId: string, variantId: string, mutate: (variant: ImportedVariant) => ImportedVariant) => updateModel(productId, modelId, (model) => ({ ...model, variants: model.variants.map((variant) => variant.id === variantId ? mutate(variant) : variant) }));
  const changeClassification = (productId: string, classification: Definition["classification"]) => setDraft((current) => { const customTemplate=current.definitions.find((item)=>item.custom)?.custom; const importedTemplate=current.definitions.find((item)=>item.importedModels?.length)?.importedModels; return {...current,definitions:current.definitions.map((item)=>item.productId!==productId?item:{...item,classification,...(classification==="MADE_TO_MEASURE"&&!item.custom&&customTemplate?{custom:structuredClone(customTemplate)}:{}),...(classification==="IMPORTED"&&!item.importedModels?.length&&importedTemplate?{importedModels:structuredClone(importedTemplate).map((model)=>({...model,id:crypto.randomUUID(),variants:model.variants.map((variant)=>({...variant,id:crypto.randomUUID()}))}))}:{})})}; });
  async function request(method: "PUT" | "POST") { setBusy(true); setFeedback(""); try { const response = await fetch("/api/admin/pricing-catalog", { method, headers: { "Content-Type": "application/json" }, ...(method === "PUT" ? { body: JSON.stringify(draft) } : {}) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "No se pudo guardar"); if (method === "PUT") setDraft(body); setFeedback(method === "PUT" ? "Borrador guardado." : `Versión ${body.version} publicada. Las propuestas anteriores conservan su snapshot.`); } catch (error) { setFeedback(error instanceof Error ? error.message : "Error"); } finally { setBusy(false); } }
  return <div className={styles.manager}>
    <div className={styles.bar}><p><b>Borrador v{draft.version}</b> · publicada v{publishedVersion}. Los precios demo no se publican sin una acción explícita.</p><div><button disabled={busy} onClick={() => request("PUT")}><Save size={16}/>Guardar borrador</button><button disabled={busy} onClick={() => request("POST")}><Send size={16}/>Publicar versión</button></div></div>
    {feedback && <div className={styles.feedback}>{feedback}</div>}
    <section className={styles.section}><h2>Tarjeta del Home</h2><p>Reemplaza únicamente la tarjeta solicitada; cerco eléctrico permanece disponible en otras partes.</p><div className={styles.grid}><label>Título<input value={draft.homeCard.title} onChange={(e)=>setDraft({...draft,homeCard:{...draft.homeCard,title:e.target.value}})}/></label><label>Destino<input value={draft.homeCard.destination} onChange={(e)=>setDraft({...draft,homeCard:{...draft.homeCard,destination:e.target.value}})}/></label><label className={styles.full}>Descripción<input value={draft.homeCard.description} onChange={(e)=>setDraft({...draft,homeCard:{...draft.homeCard,description:e.target.value}})}/></label><label className={styles.full}>Imagen provisional reemplazable<input value={draft.homeCard.image} onChange={(e)=>setDraft({...draft,homeCard:{...draft.homeCard,image:e.target.value}})}/></label><label>Orden<input type="number" value={draft.homeCard.order} onChange={(e)=>setDraft({...draft,homeCard:{...draft.homeCard,order:Number(e.target.value)}})}/></label><label>Visibilidad<select value={String(draft.homeCard.visible)} onChange={(e)=>setDraft({...draft,homeCard:{...draft.homeCard,visible:e.target.value==="true"}})}><option value="true">Visible</option><option value="false">Oculta</option></select></label></div></section>
    <section className={styles.section}><h2>Identidad y condiciones de la propuesta</h2><p>Estos datos quedan congelados dentro de cada propuesta emitida.</p><div className={styles.grid}><label>Nombre comercial<input value={draft.proposalSettings.companyName} onChange={(e)=>setDraft({...draft,proposalSettings:{...draft.proposalSettings,companyName:e.target.value}})}/></label><label>Razón social<input value={draft.proposalSettings.legalName} onChange={(e)=>setDraft({...draft,proposalSettings:{...draft.proposalSettings,legalName:e.target.value}})}/></label><label>RUC<input value={draft.proposalSettings.ruc} onChange={(e)=>setDraft({...draft,proposalSettings:{...draft.proposalSettings,ruc:e.target.value}})}/></label><label>WhatsApp (solo dígitos)<input value={draft.proposalSettings.whatsappNumber} onChange={(e)=>setDraft({...draft,proposalSettings:{...draft.proposalSettings,whatsappNumber:e.target.value.replace(/\D/g,"")}})}/></label><label>Vigencia (días)<input type="number" min="1" max="90" value={draft.proposalSettings.validityDays} onChange={(e)=>setDraft({...draft,proposalSettings:{...draft.proposalSettings,validityDays:Number(e.target.value)}})}/></label><label className={styles.full}>Condición de propuesta<input value={draft.proposalSettings.disclaimer} onChange={(e)=>setDraft({...draft,proposalSettings:{...draft.proposalSettings,disclaimer:e.target.value}})}/></label></div></section>
    <section className={styles.section}><h2>Puertas y reglas</h2><p>Importadas usan modelos y variantes cerradas. A medida usa rangos y reglas independientes.</p>{draft.definitions.filter((item)=>item.classification!=="NOT_APPLICABLE").map((definition)=><article className={styles.definition} key={definition.productId}>
      <header><h3>{definition.productId}</h3><span>{definition.classification === "IMPORTED" ? "Importada" : "A medida"}</span></header>
      <div className={styles.grid}><label>Clasificación<select value={definition.classification} onChange={(e)=>changeClassification(definition.productId,e.target.value as Definition["classification"])}><option value="IMPORTED">Puerta importada</option><option value="MADE_TO_MEASURE">Puerta a medida</option></select></label><label>Datos<select value={String(definition.demo)} onChange={(e)=>updateDefinition(definition.productId,(item)=>({...item,demo:e.target.value==="true"}))}><option value="true">Tarifa demo</option><option value="false">Tarifa validada</option></select></label></div>
      {definition.importedModels?.map((model)=><div key={model.id} className={styles.variants}><div className={styles.grid}><label>Nombre del modelo<input value={model.name} onChange={(e)=>updateModel(definition.productId,model.id,(value)=>({...value,name:e.target.value}))}/></label><label>Imagen<input value={model.image} onChange={(e)=>updateModel(definition.productId,model.id,(value)=>({...value,image:e.target.value}))}/></label></div>{model.variants.map((variant)=><div className={styles.variant} key={variant.id}><label>Medida<input value={variant.label} onChange={(e)=>updateVariant(definition.productId,model.id,variant.id,(value)=>({...value,label:e.target.value}))}/></label><label>Ancho<input type="number" step=".01" value={variant.widthM} onChange={(e)=>updateVariant(definition.productId,model.id,variant.id,(value)=>({...value,widthM:Number(e.target.value)}))}/></label><label>Alto<input type="number" step=".01" value={variant.heightM} onChange={(e)=>updateVariant(definition.productId,model.id,variant.id,(value)=>({...value,heightM:Number(e.target.value)}))}/></label><label>Acabados (separados por coma)<input value={variant.allowedFinishes.join(", ")} onChange={(e)=>updateVariant(definition.productId,model.id,variant.id,(value)=>{const allowedFinishes=e.target.value.split(",").map((entry)=>entry.trim()).filter(Boolean);return{...value,allowedFinishes,priceMinorByFinish:Object.fromEntries(allowedFinishes.map((finish)=>[finish,value.priceMinorByFinish[finish]??0]))}})}/></label>{variant.allowedFinishes.map((finish)=><label key={finish}>Precio {finish} S/<input type="number" min="0" step=".01" value={(variant.priceMinorByFinish[finish]??0)/100} onChange={(e)=>updateVariant(definition.productId,model.id,variant.id,(value)=>({...value,priceMinorByFinish:{...value.priceMinorByFinish,[finish]:Math.round(Number(e.target.value)*100)}}))}/></label>)}</div>)}<button type="button" onClick={()=>updateDefinition(definition.productId,(item)=>{const source=item.importedModels?.find((entry)=>entry.id===model.id);if(!source)return item;return{...item,importedModels:[...(item.importedModels??[]),{...structuredClone(source),id:crypto.randomUUID(),name:`${source.name} copia`,variants:source.variants.map((variant)=>({...variant,id:crypto.randomUUID()}))}]}})}><CopyPlus size={15}/>Duplicar modelo</button></div>)}
      {definition.custom&&<div className={styles.grid}><label>Ancho mínimo<input type="number" step=".01" value={definition.custom.minWidthM} onChange={(e)=>updateDefinition(definition.productId,(item)=>({...item,custom:{...item.custom!,minWidthM:Number(e.target.value)}}))}/></label><label>Ancho máximo<input type="number" step=".01" value={definition.custom.maxWidthM} onChange={(e)=>updateDefinition(definition.productId,(item)=>({...item,custom:{...item.custom!,maxWidthM:Number(e.target.value)}}))}/></label><label>Alto mínimo<input type="number" step=".01" value={definition.custom.minHeightM} onChange={(e)=>updateDefinition(definition.productId,(item)=>({...item,custom:{...item.custom!,minHeightM:Number(e.target.value)}}))}/></label><label>Alto máximo<input type="number" step=".01" value={definition.custom.maxHeightM} onChange={(e)=>updateDefinition(definition.productId,(item)=>({...item,custom:{...item.custom!,maxHeightM:Number(e.target.value)}}))}/></label><label>Mínimo facturable m²<input type="number" step=".01" value={definition.custom.minimumAreaM2} onChange={(e)=>updateDefinition(definition.productId,(item)=>({...item,custom:{...item.custom!,minimumAreaM2:Number(e.target.value)}}))}/></label><label>Instalación S/<input type="number" step=".01" value={definition.custom.installationMinor/100} onChange={(e)=>updateDefinition(definition.productId,(item)=>({...item,custom:{...item.custom!,installationMinor:Math.round(Number(e.target.value)*100)}}))}/></label>{definition.custom.areaRates.map((rate,index)=><label key={index}>Tarifa {rate.upToM2===null?"superior":`hasta ${rate.upToM2} m²`} S/m²<input type="number" step=".01" value={rate.unitPriceMinor/100} onChange={(e)=>updateDefinition(definition.productId,(item)=>({...item,custom:{...item.custom!,areaRates:item.custom!.areaRates.map((entry,rateIndex)=>rateIndex===index?{...entry,unitPriceMinor:Math.round(Number(e.target.value)*100)}:entry)}}))}/></label>)}</div>}
    </article>)}</section>
    <p className={styles.notice}><Eye size={15}/> La imagen del Home es una fotografía propia provisional. Iron Pro no se ha usado ni copiado.</p>
  </div>;
}
